### ISSUE TITLE
evaluate oxidecomputer/spdm

### ISSUE THREAD

**Issue by jyao1** [jyao1/rust-spdm#374]
https://github.com/oxidecomputer/spdm

**Comment by andrewjstone** [comment]
Hi @jyao1. I'm the primary author of that code. It's largely been abandoned. It turned out our use case just didn't match SPDM very well and we moved on. In the future it's possible it may be resurrected when we want to do things like attest 3rd party firmware running on disk drives, but I kinda doubt it. I've been assuming we'd use your version since it's much further along and has a team behind it. Regardless, we aren't there yet. I"m happy to discuss more with you offline if you are interested.

**Comment by sameo** [comment]
Thanks for the feedback @andrewjstone !
